In [10]:
import pandas as pd
from collections import Counter

In [12]:
def preprocess(file):

    '''
    input: 
    A csv file from the DREAMT dataset
    
    return: a dataframes containing 4 sleep stages (W, N1, N2, R), no mising values and certain columns dropped with high null ratios
    '''

    df = pd.read_csv(file).drop(columns=['Obstructive_Apnea', 'Central_Apnea', 'Hypopnea', 'Multiple_Events'])

    df = df[df['Sleep_Stage'] != 'P']

    return df

In [13]:
df1 = preprocess('physionet_data/S063_whole_df.csv')
df2 = preprocess('physionet_data/S064_whole_df.csv')
df3 = preprocess('physionet_data/S065_whole_df.csv')

In [26]:
dfs = [df1, df2, df3]

for df in dfs:
    print(len(df))
    print(Counter(df['Sleep_Stage']))

1397761
Counter({'N2': 768000, 'W': 366721, 'N1': 188160, 'R': 74880})
1524481
Counter({'N2': 846720, 'R': 268800, 'N1': 226560, 'W': 182401})
1620481
Counter({'W': 675840, 'N2': 568321, 'R': 184320, 'N1': 159360, 'N3': 32640})

In [37]:
df1

,TIMESTAMP,BVP,ACC_X,ACC_Y,ACC_Z,TEMP,EDA,HR,IBI,Sleep_Stage
502848,7857.000000,0.08,-55.0,-15.0,34.0,34.49,0.505120,69.53,0.796875,W
502849,7857.015625,1.08,-55.0,-15.0,34.0,34.49,0.505120,69.53,0.796875,W
502850,7857.031250,2.00,-55.0,-15.0,34.0,34.49,0.505120,69.53,0.796875,W
502851,7857.046875,2.80,-55.0,-15.0,34.0,34.49,0.505120,69.53,0.796875,W
502852,7857.062500,3.48,-55.0,-15.0,35.0,34.49,0.505120,69.53,0.796875,W
...,...,...,...,...,...,...,...,...,...,...
1900604,29696.937500,-136.42,29.0,-14.0,85.0,35.95,0.797228,73.40,0.859375,W
1900605,29696.953125,-118.55,29.0,-14.0,85.0,35.95,0.797228,73.40,0.859375,W
1900606,29696.968750,-101.48,24.0,-14.0,75.0,35.95,0.797228,73.40,0.859375,W
1900607,29696.984375,-85.39,24.0,-14.0,75.0,35.95,0.797228,73.40,0.859375,W
1900608,29697.000000,-69.51,-61.0,-9.0,48.0,35.95,0.793384,73.30,0.859375,W

In [38]:
df2

,TIMESTAMP,BVP,ACC_X,ACC_Y,ACC_Z,TEMP,EDA,HR,IBI,Sleep_Stage
636352,9943.000000,11.05,-25.0,47.0,36.0,31.61,2.328972,74.45,0.781250,W
636353,9943.015625,9.98,-25.0,47.0,36.0,31.61,2.328972,74.45,0.781250,W
636354,9943.031250,9.08,-26.0,47.0,35.0,31.61,2.328972,74.45,0.781250,W
636355,9943.046875,8.25,-26.0,47.0,35.0,31.61,2.328972,74.45,0.781250,W
636356,9943.062500,7.38,-25.0,47.0,36.0,31.61,2.328972,74.45,0.781250,W
...,...,...,...,...,...,...,...,...,...,...
2160828,33762.937500,-71.08,-26.0,-15.0,57.0,34.53,2.353032,66.10,0.890625,W
2160829,33762.953125,-71.90,-26.0,-15.0,57.0,34.53,2.353032,66.10,0.890625,W
2160830,33762.968750,-69.42,-26.0,-15.0,57.0,34.53,2.353032,66.10,0.890625,W
2160831,33762.984375,-63.36,-26.0,-15.0,57.0,34.53,2.353032,66.10,0.890625,W
2160832,33763.000000,-54.14,-26.0,-15.0,57.0,34.53,2.349190,66.15,0.890625,W

In [36]:
import os
participant_id = os.path.basename('/Users/daviddechantsreiter/Desktop/GitHub/sleep-ml/physionet_data/S055_whole_df.csv').split('.')

print(participant_id)

['S055_whole_df', 'csv']